In [2]:
import numpy as np

In [10]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [7,8,9,10]])
print a
print
print a.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7  8  9 10]]

(3L, 4L)


In [11]:
c = a
c.shape = 4,3
print c
print 
print a

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  7]
 [ 8  9 10]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  7]
 [ 8  9 10]]


In [12]:
b = a.reshape((2,-1))
print b
print 
print a

[[ 1  2  3  4  5  6]
 [ 7  8  7  8  9 10]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  7]
 [ 8  9 10]]


In [13]:
x = np.linspace(0, 2*np.pi, 10)
y = np.sin(x)
print y

[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


In [15]:
a = np.matrix([[1,2,3],
               [5,5,6],
               [7,9,9]])
print a**-1

[[-0.6         0.6        -0.2       ]
 [-0.2        -0.8         0.6       ]
 [ 0.66666667  0.33333333 -0.33333333]]
