In [5]:
import numpy as np
import math

In [8]:
np.pi

3.141592653589793

In [9]:
np.e

2.718281828459045

In [12]:
print 'pi = %.3f, e = %.3f'%(np.pi, np.e)

pi = 3.142, e = 2.718


In [18]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]])

print A

[[1 2]
 [3 4]
 [5 6]]


In [21]:
v = np.array([1,2,3])
print v

[1 2 3]


In [24]:
v = np.array([[1],[2],[3]])
print v

[[1]
 [2]
 [3]]


In [30]:
v = np.arange(1., 2., 0.1)
print v

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [31]:
v = np.arange(1, 6)
print v

[1 2 3 4 5]


In [34]:
v = np.ones([2,3])
print v

[[1. 1. 1.]
 [1. 1. 1.]]


In [35]:
v = 2*np.ones([2,3])
print v

[[2. 2. 2.]
 [2. 2. 2.]]


In [38]:
v = np.random.random([3,3])
print v

[[0.57961605 0.23289289 0.55181109]
 [0.66826522 0.70062848 0.81522231]
 [0.89973197 0.01421603 0.77578592]]


In [39]:
w = np.zeros([1,3])
print w

[[0. 0. 0.]]


In [42]:
I = np.eye(5)
print I

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [49]:
A = np.array([[1,2],[3,4],[5,6]])
print A[2,1]
print A[:,1]
print A[1,:]

6
[2 4 6]
[3 4]


In [51]:
print A[(0,2),:] # Row 0 & 2

[[1 2]
 [5 6]]


In [52]:
A[:,1] = [10, 11, 12]
print A

[[ 1 10]
 [ 3 11]
 [ 5 12]]


In [74]:
B = np.array([100,101,102]).reshape(3,1)
A.reshape(3,2)
np.append(A, B, axis=1)

array([[  1,  10, 100],
       [  3,  11, 101],
       [  5,  12, 102]])